[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["npm install -g corepack@0.24.1 && corepack enable && pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm --filter @prediction-market/api build"]

[start]
cmd = "node apps/api/dist/main.js"
