apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prediction-market-prod

bases:
  - ../../base

namePrefix: prod-

commonLabels:
  environment: production

patches:
  - path: api-patch.yaml
  - path: web-patch.yaml

configMapGenerator:
  - name: api-config
    behavior: merge
    literals:
      - NODE_ENV=production
      - CORS_ORIGINS=https://example.com

images:
  - name: prediction-market-api
    newTag: v1.0.0
  - name: prediction-market-web
    newTag: v1.0.0
