apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prediction-market

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - api-deployment.yaml
  - web-deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
