apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  labels:
    app.kubernetes.io/name: prediction-market
    app.kubernetes.io/component: api
type: Opaque
stringData:
  JWT_SECRET: "CHANGE_ME_TO_A_SECURE_VALUE_AT_LEAST_32_CHARS"
  DB_HOST: "postgres-service"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "CHANGE_ME"
  DB_DATABASE: "prediction_market"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
